CREATE USER "udd" WITH PASSWORD 'udd';
CREATE USER "udd-mirror" WITH PASSWORD 'udd-mirror';
ALTER DEFAULT PRIVILEGES FOR USER "udd" IN SCHEMA "public" GRANT SELECT ON TABLES TO "udd";
ALTER DEFAULT PRIVILEGES FOR USER "udd-mirror" IN SCHEMA "public" GRANT SELECT ON TABLES TO "udd-mirror";
